version: '3.1'

services:
  mysql8:
    image: mysql:8.0.28
    container_name: mysql8_db
    command: --default-authentication-plugin=mysql_native_password
    privileged: true
#    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/houzw/rundata/DATA_mysql/data:/var/lib/mysql
      - /home/houzw/rundata/DATA_mysql/log:/var/log/mysql
      - ./my8.cnf:/etc/my.cnf
    deploy:
      resources:
        limits:
          memory: 2G


  mysql8_adminer:
    image: adminer:4.8.1
    container_name: mysql8_adminer
#    restart: always
    ports:
      - 8080:8080
