version: '2'
services:
  kafka_zk:
    container_name: kafka_zk
    image: zookeeper:3.8.1
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      #KAFKA_ADVERTISED_HOST_NAME: 192.168.105.60
      KAFKA_ADVERTISED_HOST_NAME: 172.55.55.55
        #KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: kafka_zk:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
