version: '2'
services:
  rmqnamesrv:
    image: apache/rocketmq:4.9.1
    container_name: rmq_namesrv
    ports:
      - 9876:9876
    volumes:
      - ./data/logs:/root/logs
    command: sh mqnamesrv
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      rmq:
        aliases:
          - rmqnamesrv
  rmqbroker:
    image: apache/rocketmq:4.9.1
    container_name: rmq_broker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    environment:
      MAX_HEAP_SIZE: 512m
      HEAP_NEWSIZE: 300m
    volumes:
      - ./data/logs:/root/logs
      - ./data/store:/root/store
      - ./broker.conf:/home/rocketmq/rocketmq-4.9.1/conf/broker.conf
    # 这个原始启动脚本获取容器中的内存有问题，默认给的堆空间太大了8G
    #command: sh -x mqbroker -n rmqnamesrv:9876 -c ../conf/broker.conf
    #command: sh -x /home/rocketmq/rocketmq-4.9.1/bin/runbroker.sh org.apache.rocketmq.broker.BrokerStartup -n rmqnamesrv:9876 -c ../conf/broker.conf
    command: 'java -server -Xmx512M -Xmn300M -Djava.ext.dirs=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.302.b08-0.el7_9.x86_64/jre/lib/ext:/home/rocketmq/rocketmq-4.9.1/lib -cp .:/home/rocketmq/rocketmq-4.9.1/bin/../conf: org.apache.rocketmq.broker.BrokerStartup -n rmqnamesrv:9876 -c ../conf/broker.conf'
    #command: env
    depends_on:
      - rmqnamesrv
    deploy:
      resources:
        limits:
          memory: 4G
    networks:
      rmq:
        aliases:
          - rmqbroker
  rmqconsole:
    image: styletang/rocketmq-console-ng:1.0.0
    container_name: rmq_console
    ports:
      - 8001:8080
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=rmqnamesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    depends_on:
      - rmqnamesrv
    networks:
      rmq:
        aliases:
          - rmqconsole

networks:
  rmq:
    name: rmq
    driver: bridge
