version: '2'
services:
  rmqnamesrv:
    image: apache/rocketmq:4.9.1
    container_name: rmq_namesrv
    ports:
      - 9876:9876
    volumes:
      - ./data/logs:/home/rocketmq/logs
    command: sh mqnamesrv
    networks:
      rmq:
        aliases:
          - rmqnamesrv
  rmqbroker:
    image: apache/rocketmq:4.9.1
    container_name: rmq_broker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    volumes:
      - ./data/logs:/home/rocketmq/logs
      - ./data/store:/home/rocketmq/store
      - ./broker.conf:/home/rocketmq/rocketmq-4.9.1/conf/broker.conf
    command: sh mqbroker -n rmqnamesrv:9876 -c ../conf/broker.conf
    depends_on:
      - rmqnamesrv
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      rmq:
        aliases:
          - rmqbroker
  rmqconsole:
    image: styletang/rocketmq-console-ng:1.0.0
    container_name: rmq_console
    ports:
      - 8001:8080
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=rmqnamesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    depends_on:
      - rmqnamesrv
    networks:
      rmq:
        aliases:
          - rmqconsole

networks:
  rmq:
    name: rmq
    driver: bridge
