---
apiVersion: v1
kind: Service
metadata:
  name: traefiktcp
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:
    - protocol: TCP
      port: 3080
      name: web
      targetPort: 3080
      nodePort: 3080
    - protocol: TCP
      port: 8180
      name: admin
      targetPort: 8180
      nodePort: 8180
    - protocol: TCP
      port: 8100
      name: tcpep
      targetPort: 8100
      nodePort: 8100
---
apiVersion: v1
kind: Service
metadata:
  name: traefikudp
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:
    - protocol: UDP
      port: 9100
      name: udpep
      targetPort: 9100
      nodePort: 9100
