version: '3.1'

# docker run --name wiz --restart=always -it -d -v  ~/wizdata:/wiz/storage -v  /etc/localtime:/etc/localtime -p 80:80 -p 9269:9269/udp  wiznote/wizserver

services:
  wiznote_oss:
    image: wiznote/wizserver:latest
    container_name: wiznote_oss
    ports:
      - 3480:80
      - 3406:3306
      - 3469:9269
#    environment:
#      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/houzw/rundata/DATA_wiznote/storage2:/wiz/storage
      - /etc/localtime:/etc/localtime
    deploy:
      resources:
        limits:
          memory: 10G
