version: '2'
services:
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.12.0
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
