version: '3.1'

services:
  db2_2:
    image: ibmcom/db2:11.5.8.0
    container_name: db2_2
    privileged: true
    ports:
      - 50002:50000
    environment:
      LICENSE: accept
      DB2INST1_PASSWORD: db2inst1
      DBNAME: testdb
    volumes:
      - /home/houzw/rundata/DATA_db2/database2:/database
    deploy:
      resources:
        limits:
          memory: 2G

