version: '3.1'

services:
  db2_setablecodepage_1:
    image: houzw/db2_setablecodepage:v1
    container_name: db2_setablecodepage_1
    privileged: true
    ports:
      - 50004:50000
    environment:
      LICENSE: accept
      DB2INST1_PASSWORD: db2inst1
      DBNAME: testdb
      DB_CODESET: GB18030
      DB_TERRITORY: cn
    volumes:
      - /home/houzw/rundata/DATA_db2/database1_gb18030:/database
    deploy:
      resources:
        limits:
          memory: 2G

