version: '3.1'

services:
  db2_gbk_1:
    image: houzw/db2_gbk:v1
    container_name: db2_gbk_1
    privileged: true
    ports:
      - 50003:50000
    environment:
      LICENSE: accept
      DB2INST1_PASSWORD: db2inst1
      DBNAME: testdb
    volumes:
      - /home/houzw/rundata/DATA_db2/database1_gbk:/database
    deploy:
      resources:
        limits:
          memory: 2G

