version: '2'
services:
  #  kafka_apcache_zk:
  #    container_name: kafka_apache_zk
  #    image: zookeeper:3.8.1
  kafka_apache_sasl:
    #image: apache/kafka:3.7.0_hzw
    image: apache/kafka:3.7.0
    container_name: kafka_apache_sasl
    ports:
      - "9093:9092"
    environment:
      hzw: hzw
      KAFKA_hzw: hzw
      CLUSTER_ID: 3q4TyRC4SXKgfoSIHqRlpA
      #KAFKA_ADVERTISED_LISTENERS: 'SASL_PLAINTEXT://kafka:9092'
      #KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092'
      #KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
      KAFKA_ZOOKEEPER_CONNECT: ""
      #KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      #KAFKA_INTER_BROKER_PROTOCOL_VERSION: 3_7-IV4
      #KAFKA_LOG_CLEANER_BACKOFF_MS: 10000
      #KAFKA_BROKER_ID: 1
      #KAFKA_ADVERTISED_PORT: 9092
      ##KAFKA_ZOOKEEPER_CONNECT: kafka_apache_zk:2181
      #KAFKA_ZOOKEEPER_CONNECT: ''
      #KAFKA_ADVERTISED_HOST_NAME: kafka
      #KAFKA_LISTENERS: SASL_PLAINTEXT://:9095
      #KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
      #KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      #KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      #KAFKA_CLIENT_USERS: test
      #KAFKA_CLIENT_PASSWORDS: 123456
      #KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
      #KAFKA_HZW: hzw
      #KAFKA_ADVERTISED_HOST_NAME: 192.168.105.60
      #KAFKA_ADVERTISED_HOST_NAME: 172.55.55.55
      #KAFKA_ZOOKEEPER_CONNECT: kafka_zk:2181
    volumes:
      - ./kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
